select p.PRODUCT_ID, p.PRODUCT_NAME, sum(p.PRICE * o.AMOUNT) as 'TOTAL_SALES'
from FOOD_ORDER o
join FOOD_PRODUCT p on p.PRODUCT_ID = o.PRODUCT_ID
where o.PRODUCE_DATE >= '2022-05-01' and o.PRODUCE_DATE <= '2022-05-31'
group by p.PRODUCT_ID
order by TOTAL_SALES desc, p.PRODUCT_ID
;