SELECT
  e.EMP_NO,
  e.EMP_NAME,
  CASE
    WHEN g.AVG_SCORE >= 96 THEN 'S'
    WHEN g.AVG_SCORE >= 90 THEN 'A'
    WHEN g.AVG_SCORE >= 80 THEN 'B'
    ELSE 'C'
  END AS GRADE,
  CASE
    WHEN g.AVG_SCORE >= 96 THEN e.SAL * 0.20
    WHEN g.AVG_SCORE >= 90 THEN e.SAL * 0.15
    WHEN g.AVG_SCORE >= 80 THEN e.SAL * 0.10
    ELSE 0
  END AS BONUS
FROM HR_EMPLOYEES e
JOIN (
  SELECT EMP_NO, AVG(SCORE) AS AVG_SCORE
  FROM HR_GRADE
  WHERE YEAR = 2022
  GROUP BY EMP_NO
) g ON g.EMP_NO = e.EMP_NO
ORDER BY e.EMP_NO;